### PR TITLE
feat: export TrackingContext

### PR DESCRIPTION
**Pull request by nicosommi**
I'm creating a TrackingView wrapper from a consumer, and I would like to mock and check the view is set properly in the context so that I can check it's sending the proper name, as well as maybe get the current value for logging, for testing purposes.

This is the more flexible but simple way I found to do it.

Note: I tried with setting up a local reference to collector with local changes, but is not so easy as it has a duplicate version of react and all that story that throw errors on hooks. Also, modifying the source is very awkward since is only bundled and obfuscated.

### CODE REVIEW

**Comment by nicosommi** [comment]
For more context, when adding the integration on a consumer, there is nothing rendered to the final html, only the context provider, so there is nothing new on the snapshot or the rendered page, but only a component on shallow renders.

On the other hand, as we send the events indirectly via the handler function, there is no way to check the event was dispatched with the correct values.

So the whole thing feels like a shot in the dark specially with also third party integrations like circuit button, etc.

With the context I expect to solve all of these things in the short term since I can put a spy in the dispatch and assert and/or log against it or any other value, like in my case the view name.

**Review by connor-baer — APPROVED** [review]

**Comment by connor-baer** [comment]
@nicosommi I updated the PR title to follow the conventional commit guidelines since Collector is automatically published with [semantic release](https://github.com/semantic-release/semantic-release).

**Comment by nicosommi** [comment]
> @nicosommi I updated the PR title to follow the conventional commit guidelines since Collector is automatically published with [semantic release](https://github.com/semantic-release/semantic-release). Please make sure to use this as the commit message when (squash) merging.

👍  Thanks. I just realized that I may be able to do this already using the `TrackingRoot`. I will give that a shot before moving forward with this.

**Comment by nicosommi** [comment]
Yep, my bad. Included members are enough.

**Pull request closed without merging**
